#!/bin/sh
set -e
. /usr/share/debconf/confmodule

db_input critical backend/mysql_root || true
db_go
db_input critical backend/mysql_dba_user || true
db_go
db_input critical backend/mysql_dba_password || true
db_go

