#!/bin/sh
. /usr/share/debconf/confmodule


db_up() {
  #Check if mysql is started
  /etc/init.d/mysql status > /dev/null || /etc/init.d/mysql start >/dev/null 2>&1

  echo -n "INFO: Waiting for mysql to be up..."
  CPT=0
  TIMEOUT=60
  #TODO add waiting 
  echo " Done"
}

db_configure() {
    db_get backend/mysql_root
    ROOT_PW=$RET

    db_get backend/mysql_dba_user
    DBA_USER=$RET

    db_get backend/mysql_dba_password
    DBA_PASS=$RET
       
   
    # add user and add schema and data
    echo "create database if not exists unifiedviews;" | mysql --password=$ROOT_PW
    echo "drop user $DBA_USER;" | mysql --password=$ROOT_PW || true
    echo "create user $DBA_USER identified by '$DBA_PASS';" | mysql --password=$ROOT_PW
    echo "grant ALL on unifiedviews.* to $DBA_USER;" | mysql --password=$ROOT_PW
    mysql -u $DBA_USER --password=$DBA_PASS unifiedviews < \
    /usr/share/unifiedviews/mysql/schema.sql >> /var/log/unifiedviews/sql-install.log 2>&1
    mysql -u $DBA_USER --password=$DBA_PASS unifiedviews < \
    /usr/share/unifiedviews/mysql/data.sql >> /var/log/unifiedviews/sql-install.log 2>&1
    mysql -u $DBA_USER --password=$DBA_PASS unifiedviews < \
    /usr/share/unifiedviews/mysql/core-plugin.sql >> /var/log/unifiedviews/sql-install.log 2>&1
    #update backend config
    sed --in-place \
    -e "s/database.sql.hostname = .*/database.sql.hostname = $address_host/" \
    -e "s/database.sql.port = .*/database.sql.port = 3306/" \
    -e "s/database.sql.user = .*/database.sql.user = $DBA_USER/" \
    -e "s/database.sql.password = .*/database.sql.password = $DBA_PASS/" \
    -e "s/database.rdf.hostname = .*/database.rdf.hostname = $address_host/" \
    -e "s/database.rdf.port = .*/database.rdf.port = $address_port/" \
    -e "s/database.rdf.user = .*/database.rdf.user = $username/" \
    -e "s/database.rdf.password = .*/database.rdf.password = $password/" \
    /etc/unifiedviews/backend-config.properties
}

prepare_dir() { 
    mkdir -p /var/log/unifiedviews/
    chown tomcat7:tomcat7 /var/log/unifiedviews/
    
    mkdir -p /usr/share/unifiedviews
    chown tomcat7:tomcat7 /usr/share/unifiedviews

    mkdir -p /var/log/unifiedviews/backend
    chown tomcat7:tomcat7 /var/log/unifiedviews /var/log/unifiedviews/backend

    mkdir -p /var/lib/unifiedviews/backend/working
    chown tomcat7:tomcat7  /var/lib/unifiedviews/backend  /var/lib/unifiedviews/backend/working

    mkdir -p /var/lib/unifiedviews/target
    chown tomcat7:tomcat7 /var/lib/unifiedviews/target /var/lib/unifiedviews/target

    mkdir -p /var/lib/unifiedviews/target/
    chown tomcat7:tomcat7 /var/lib/unifiedviews/backend/working
    
    mkdir -p ~tomcat7/.eclipse
    chown -R tomcat7:tomcat7 ~tomcat7/.eclipse

    chown tomcat7:tomcat7 /usr/share/unifiedviews
    chmod g+w /usr/share/unifiedviews
    chmod +x  /usr/sbin/run_unifiedviews_backend
    chown tomcat7:tomcat7 /usr/sbin/run_unifiedviews_backend
  
    chmod +x  /etc/init.d/unifiedviews-backend

    chown tomcat7:tomcat7 /usr/share/tomcat7
    
    mkdir -p /var/lib/unifiedviews/target/lib
    chown tomcat7:tomcat7 /var/lib/unifiedviews/target/lib
    
    mkdir -p /var/lib/unifiedviews/target/dpu
    chown tomcat7:tomcat7 /var/lib/unifiedviews/target/dpu
    
}

service_backend_start() {
    if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
        invoke-rc.d unifiedviews-backend start || true
    else
        service unifiedviews-backend start || true
    fi
}

case "$1" in
  configure)
    db_up
    prepare_dir
    db_configure
    service_backend_start
    db_stop
    
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
  ;;

  *)
    echo "$0 called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac