#!/bin/sh

set -e

if [ -x /etc/init.d/unifiedviews-backend ]; then
  if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
    invoke-rc.d unifiedviews-backend stop || true
  else
    /etc/init.d/unifiedviews-backend stop || true
  fi
fi

