#!/bin/sh

### BEGIN INIT INFO
# Provides:             unifiedviews-backend
# Required-Start:       $network $named
# Required-Stop:        $network $named
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Starts unifiedviews-backend service
### END INIT INFO

set -e

PATH=/bin:/usr/bin:/sbin:/usr/sbin
NAME=unifiedviews-backend
DESC="unifiedviews-backend service"
DEFAULT=/etc/default/$NAME

if [ `id -u` -ne 0 ]; then
  echo "You need root privileges to run this script"
  exit 1
fi

. /lib/lsb/init-functions

if [ -r /etc/default/rcS ]; then
. /etc/default/rcS
fi

# The first existing directory is used for JAVA_HOME (if JAVA_HOME is not defined in $DEFAULT)
JDK_DIRS="/usr/lib/jvm/java-7-oracle /usr/lib/jvm/java-7-openjdk /usr/lib/jvm/java-7-openjdk-amd64 /usr/lib/jvm/java-7-openjdk-i386"

# Look for the right JVM to use
for jdir in $JDK_DIRS
do
  if [ -r "$jdir/bin/java" -a -z "${JAVA_HOME}" ]; then
    JAVA_HOME="$jdir"
  fi
done
export JAVA_HOME

JAVA_OPTS="-DconfigFileLocation=/etc/unifiedviews/backend-config.properties"
BACKEND_OPTS=

# overwrite settings from default file
if [ -f "$DEFAULT" ]; then
. "$DEFAULT"
fi

case "$1" in
start)
  log_daemon_msg "Starting $NAME"
  start-stop-daemon -d /usr/share/unifiedviews -c tomcat7 -g tomcat7 -S -b -u tomcat7 -x $JAVA_HOME/bin/java -- $JAVA_OPTS -jar backend-1.3.0.jar $BACKEND_OPTS
  log_end_msg 0
  ;;
stop)
  log_daemon_msg "Stopping $NAME"
  start-stop-daemon -K -R 30 -u tomcat7 -x $JAVA_HOME/bin/java
  log_end_msg 0
  ;;
status)
  PID=$(start-stop-daemon --test -o -K -u tomcat7 -x $JAVA_HOME/bin/java)
  case "$PID" in
  *'to '[0-9]*)
    PID="${PID##*to }"
    echo "$NAME is running, process $PID"
    ;;
  *)
    echo "$PID"
    ;;
  esac
  ;;
esac

